name: Deploy React App
on: push
jobs: 
  deply:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test Application
        run: npm run test
      - name: Install Lint
        run: npm install --save-dev eslint-config-react-app eslint
      - name: Lint Application
        run: npm run lint
      - name: Build Application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
